### ISSUE TITLE
Epic: BAA - Improve Slope Analysis

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#1]
## Description
_Brief summary of what this Epic is, whether it's a larger project, goal, or user story. Describe the job to be done, which persona this Epic is mainly for, or if more multiple, break it down by user and job story._
This Epic is to improve the current Buildable Area Analysis Slope Anaylsis in a number of ways. First, to use higher resolution data in the analysis. Second, to allow users to perform the use different slope levels for different aspects.

## Acceptance criteria and must have scope
- [ ] Slope analysis uses higher resolution data available from: [3DEP](https://elevation.nationalmap.gov/arcgis/rest/services/3DEPElevation/ImageServer)
- [ ] Users can select different slope levels for different aspects in the BAA form
- [ ] 
## Stakeholders
- Client Success
- QA

## Tickets: 
- [ ] https://github.com/anderson-optimization/task-geoanalysis/issues/403
- [ ] https://github.com/anderson-optimization/task-geoanalysis/issues/125

**Comment by MeganKYoung** [comment]
@disbr007 I think we should deprioritize this one. We do get requests for it very periodically, but it doesn't feel as high value as any of the other stuff we've considered. 
Feature Request: Buildable Area - Minimum slope hazard size (allow users to mark small slope sections as buildable) via field/parameter on BAA form  task-geoanalysis#11
