### ISSUE TITLE
Epic: ETL User Driven Improvements

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#10]
## Rationale ##
Users currently need to submit layer requests to CS, who pass them onto the GIS team, who then integrates them. We are close to releasing the functionality to allow users to Drag and Drop a shapefile onto the map and see it in their layers menu. In that release, users will only be able to supply a name for the layer they are creating. 

This epic is to make improvements to that process to allow users to customize more about the way the layer will be integrated. The possibilities for these improvements are basically all of the different types of functionality that can be requested in our current layer integration process:

- Layer Name:
- Source Name:
- Source Hyperlink:
- Group Header Name:
- Pop-up Header Field:
- Opacity:
- Legend (yes/no):
_Functionality_
- Copy button OR Create (Asset) button:
- Create Asset Field Mapping ( source fields to asset metadata fields. These can be a single field or a combinations of multiple fields and text, eg:
    name:
    id:
    description:
    substation_voltage:
    transmission_voltage:
    additional options below
)
- Meta Keywords / Tags - help users more easily search/filter for layers by common keywords/tags

These options are all currently available to be used in the main layer ingestion code that is used by Shapefile Drag and Drop (SDD) (`handle_new_source.py` in the `aoetl` repository). So the primary work to be done is to update the SDD form to have inputs for all of the above.

Additionally, an "Import" button should be added to the frontend to signal to users that they can integrate their own layers.

## Owner ##
@disbr007 

## Stakeholder Point of Contact ##
@disbr007 

## Dependencies ##
- Shapefile Drag and Drop

## Issues ##
- [ ]  Update shapefile drag and drop form to accept additional arguments
- [ ]  Pass arguments to `handle_new_source.py` (it may make sense to attempt to actually import `hns` into the SDD code rather than calling as a subprocess. If so:
  - [ ] Update `aoetl` / `handle_new_source` to make the primary `hns` function importable

## Acceptance criteria ##
- [ ] Users can provide additional arguments to the SDD form and have more control over the functionality of the resulting layer.
