### ISSUE TITLE
Epic: GIS Team Tech Debt

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#15]
## Rationale ##
The repos managed by the GIS Team have accumulated tech debt. These are things that make day-to-day operations and development more challenging. This epic is to house all of these items in one place.

## Owner ##
@disbr007 

## Issues ##

- [ ]  task-geoanalysis:
  - [ ]  CICD tests which intermittently fail, for reasons unrelated to code (infra, auth, etc.)
  - [ ] Switch to using geodataframes, rather than passing features, srs, etc. around
- [ ] aoetl:
  - [ ] run full test suite in CICD (only unit tests used currently)
  - [ ] break up `handle_new_source.py` monolith - extremely long, nested script used to integrate layers
- [ ] GeoServer:
  - [ ] GeoWebCache
  - [ ] Remove unused layers (and from database)
