### ISSUE TITLE
Epic: Shapefile Drag and Drop

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#2]
## Description and Rationale ##
Allowing users to create layers via dragging and dropping a shapefile will allow them to see their own layers instantly in AO, rather than waiting for the a layers integration request to be processed. This also alleviates workload from the GIS Team, and is a Leeward contract requirement.

## Stakeholders ##
Point of Contact: Jeff D
- GIS Team
- Frontend Team
- Client Success / Leeward POC

## Dependencies ##
- [x] aoetl.handle_new_source -> deploy to AO functional

## Context ##
Currently shapefiles must be integrated via a "Layer Integration Request" that can take days to weeks depending on queue of requests and complexity of ask. 

## Issues ##
- [x] https://github.com/anderson-optimization/task-ops/issues/40
- [x] https://github.com/anderson-optimization/task-ops/issues/38
- [x] https://github.com/anderson-optimization/task-ops/issues/28
- [x] https://github.com/anderson-optimization/task-ops/issues/20
- [x] https://github.com/anderson-optimization/task-ops/issues/19
- [x] https://github.com/anderson-optimization/task-ops/issues/23

## Bugs ##
- [x] https://github.com/anderson-optimization/ao-frontend/issues/3588

## Acceptance criteria ##
As a user, if I drag and drop a shapefile (zipped, or multiple files comprising a shapefile) onto any(?) AO map, I should be presented with a form with options for how to integrate the shapfile, primarily what name should appear in the Layer Catalog. After submitting the form, it should be displayed and able to be interacted with the layer in the layers menu.

**Comment by MeganKYoung** [comment]
@disbr007 Does GIS team need to help with allowing multiple shapefiles to be imported at one time?

**Comment by disbr007** [comment]
@MeganKYoung yes, it's mostly us, may not be any frontend depending on how it's set up now.

**Comment by disbr007** [comment]
@MeganKYoung that FR is also tracked in #10

**Comment by MeganKYoung** [comment]
@disbr007 Got it -- does it make sense to link it to this Epic or is there a reason not to add it as a task here? 

Also, it looks like you linked a different ticket than intended? The one you linked is this one to make sure that the catalog gets sorted by priority if prescribed: https://github.com/anderson-optimization/ao-frontend/issues/3616

**Comment by disbr007** [comment]
> @disbr007 Got it -- does it make sense to link it to this Epic or is there a reason not to add it as a task here?

No, it's already included in the follow up to this Epic: [Epic: Layer Import Improvements (Shapefile D+D Follow Up) #10 ](https://github.com/anderson-optimization/gis-team-api/issues/10)

> Also, it looks like you linked a different ticket than intended? The one you linked is this one to make sure that the catalog gets sorted by priority if prescribed: [anderson-optimization/ao-frontend#3616](https://github.com/anderson-optimization/ao-frontend/issues/3616)

Hmm, not sure what you mean - where did I link that frontend ticket?

**Comment by disbr007** [comment]
Released this work to prod in task-ops v0.1.12!
