### ISSUE TITLE
Epic: Capacity Mapping Improvements

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#4]
## Stakeholders ##
Point of contact: @disbr007 
- GIS Team
- Client Success

## Dependencies ##
- [ ] Agreement with additional/alternative data provider

## Context ##
We currently are integrating capacity data from Continuum Associates. 

## Issues ##
**Improving Mapping:**
- [ ] Continuum Mapping
  - [ ] Get demo data
  - [ ] Explore Continuum mapping process
  - [ ] Plan to improve Continuum mapping 
  - [ ] Implement improved Continuum mapping
- [ ] Siemens
  - [ ] Get demo data
  - [ ] Explore Siemens mapping process
  - [ ] Plan to improve Siemens mapping
  - [ ] Implement improved mapping

## Acceptance criteria ##
- [ ] Improve and/or take ownership of, the process of third party capacity data providers.

**Comment by disbr007** [comment]
Closing as not planned.
