### ISSUE TITLE
Epic: Catalog - Layer Health Checks

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#7]
## Rationale ##
Layers often "break", most often due to the server hosting the data going down, changing url, etc. Layer functionality can also break for the same reason or due to code changes.

We want to know when this happens before users report the issue. Automating "health checks" for each layer and saving the results in the layer config will allow us to do that.

## Owner ##
@disbr007 

## Stakeholder Point of Contact ##
@disbr007 

## Issues ##
- [ ] Add metadata fields to layer definition schema (repo: aolayers)
- [ ] Ability to "fetch one" for each layer type (repo: tbd)
- [ ] Automation to "fetch one" for each layer, starting with system layers and statelayers (repo: tbd)
- [ ] Tests for other functionality listed in acceptance criteria
- [ ] Automated alerts when a layer fails

## Acceptance criteria ##
- [ ] Allow users to tell whether a layer is functioning properly at a glance. This includes: 
  - fetching features/tiles (this is the most important one - is the server responding?)
  - displaying legends
  - clicks/popups
  - polygon select
  - copy/create
