### ISSUE TITLE
Epic: Automated Layer Updates

### ISSUE THREAD

**Issue by disbr007** [anderson-optimization/gis-team-api#8]
## Rationale ##
Currently layers are completely manually updated, both determining if an update is necessary and the process of updating. Automating both of these steps will save a significant amount of time, both for developers and CS.

## Owner ##
@disbr007 

## Stakeholder Point of Contact ##
@disbr007 

## Issues ##
- [ ] Determine if a layer requires updating based on IDs
- [ ] Determine if a layer requires updating based on comparing features
- [ ] Run the above checks automatically (e.g. weekly) - alert if update required
- [ ] If a layer requires updating, do so automatically (maintaining the same `accessKey`)

## Acceptance criteria ##
- [ ] Layers are checked for updates automatically
- [ ] Layers are updated automatically
